//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGAGrabber
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSDIPEntities : DbContext
    {
        public DSDIPEntities()
            : base("name=DSDIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LGA> LGAs { get; set; }
        public virtual DbSet<SA3> SA3 { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<LGAWOEId> LGAWOEIds { get; set; }
    }
}
