//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGAGrabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGA
    {
        public string LGACode2016 { get; set; }
        public string LGALongCode2016 { get; set; }
        public string LGAName2016 { get; set; }
        public string StateCode { get; set; }
        public Nullable<int> StateId { get; set; }
        public string LGACode2011 { get; set; }
        public string LGALongCode2011 { get; set; }
        public string LGAName2011 { get; set; }
        public Nullable<bool> Map { get; set; }
        public Nullable<bool> Dropdown { get; set; }
    }
}
