//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGAGrabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGAWOEId
    {
        public int Id { get; set; }
        public string LGACode { get; set; }
        public string LGAName { get; set; }
        public string WOEName { get; set; }
        public int WOEId { get; set; }
        public string State { get; set; }
        public string Type { get; set; }
    }
}
