//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGAGrabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA3
    {
        public string SA3Code2016 { get; set; }
        public string SA3Name2016 { get; set; }
        public Nullable<int> StateId { get; set; }
        public string StateCode { get; set; }
        public Nullable<bool> AlwaysInclude { get; set; }
        public string SA3Code2011 { get; set; }
        public string SA3Name2011 { get; set; }
        public Nullable<bool> Map { get; set; }
        public Nullable<bool> Dropdown { get; set; }
    }
}
